export const banks: { [key: string]: string } = {
  alior: 'Alior Bank',
  pocztowy: 'Bank Pocztowy',
  bgk: 'Bank Gospodarstwa Krajowego',
  bgz: 'BGŻ',
  bnpparibas: 'BNP Paribas',
  bos: 'BOŚ Bank',
  bph: 'BPH',
  bps: 'BPS',
  bzwbk: 'BZWBK',
  citibank: 'Citi Handlowy',
  creditagricole: 'Credit Agricole',
  db: 'Deutsche Bank',
  dnbnord: 'Bank DnB Nord',
  eurobank: 'Eurobank',
  getin: 'Getin Bank',
  ing: 'ING Bank Śląski',
  mbank: 'mBank',
  millennium: 'Millenium',
  nordea: 'Nordea Bank',
  pekao: 'Pekao SA',
  pkobp: 'PKO BP',
  polbank: 'Polbank',
  raiffeisen: 'Raiffeisen',
  santander: 'Santander Bank Polska',
  sg: 'Santander Consumer Bank',
  vw: 'Volkswagen Financial Services',
  nestbank: 'Nest Bank',
};
