export enum ActionTypes {
  // auth
  AUTHENTICATE_START = 'AUTHENTICATE_START',
  AUTHENTICATE_END = 'AUTHENTICATE_END',
  AUTHENTICATE_FAIL = 'AUTHENTICATE_FAIL',
  REGISTER_START = 'REGISTER_START',
  REGISTER_END = 'REGISTER_END',
  REGISTER_FAIL = 'REGISTER_FAIL',
  SET_AUTHENTICATION_ERROR = 'SET_AUCTHENTICATION_ERROR',
  LOGOUT = 'LOGOUT',

  // historical rates
  SET_CURRENCY = 'SET_CURRENCY',
  SET_ACTIVE_STATUS = 'SET_ACTIVE_STATUS',
  SET_CURRENT_RANGE = 'SET_CURRENT_RANGE',
  SET_HISTORICAL_RATES = 'SET_HISTORICAL_RATES',
  SET_HISTORICAL_RATES_LOADING = 'SET_HISTORICAL_RATES_LOADING',
  SET_HISTORICAL_RATES_ERROR = 'SET_HISTORICAL_RATES_ERROR',
}
