export enum ActionTypes {
  AUTHENTICATE_START = 'AUTHENTICATE_START',
  AUTHENTICATE_END = 'AUTHENTICATE_END',
  AUTHENTICATE_FAIL = 'AUTHENTICATE_FAIL',
  REGISTER_START = 'REGISTER_START',
  REGISTER_END = 'REGISTER_END',
  REGISTER_FAIL = 'REGISTER_FAIL',
  SET_ERROR = 'SET_ERROR',
  LOGOUT = 'LOGOUT',
}
